version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
  
  after_build:
- 7z a SpikeFromAppveyor.zip "c:\projects\bike-game\cargame code\Debug\3D Physics - class6.exe"
- 7z a SpikeFromAppveyor.zip "%APPVEYOR_BUILD_FOLDER%\Bike-game\Game"
- 7z a SpikeFromAppveyor.zip "%APPVEYOR_BUILD_FOLDER%\Bike-game\*.dll"
- 7z a SpikeFromAppveyor.zip "%APPVEYOR_BUILD_FOLDER%\Bike-game\README.md"

artifacts:
- path: Bike-gameAppveyor.zip
