version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
  
before_build:
- echo %APPVEYOR_BUILD_FOLDER%\CarGame Code\Game
- cd %APPVEYOR_BUILD_FOLDER%\CarGame Code\Game
  
after_build:
- cmd: mkdir %APPVEYOR_BUILD_FOLDER%\BikeGame
- cmd: copy "%APPVEYOR_BUILD_FOLDER%\CarGame Code\Debug\3D Physics - class6.exe" %APPVEYOR_BUILD_FOLDER%\BikeGame
- cmd: copy "%APPVEYOR_BUILD_FOLDER%\CarGame Code\Game" %APPVEYOR_BUILD_FOLDER%\BikeGame
- cmd: copy "%APPVEYOR_BUILD_FOLDER%\CarGame Code\Game" %APPVEYOR_BUILD_FOLDER%\BikeGame
- cmd: move %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\BikeGame
- 7z a Bike-GameRelease.zip %APPVEYOR_BUILD_FOLDER%\BikeGame

artifacts:
- path: Bike-GameRelease.zip
